2022-09-25 09:47:40 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 09:47:40 <info> (App.ts:29) undefined '❗️Error in Create users Table : ' Error
    at Query.run (C:\_git\Portfolio\backend\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\_git\Portfolio\backend\node_modules\sequelize\src\sequelize.js:641:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MySQLQueryInterface.createTable (C:\_git\Portfolio\backend\node_modules\sequelize\src\dialects\abstract\query-interface.js:229:12)
    at async Function.sync (C:\_git\Portfolio\backend\node_modules\sequelize\src\model.js:1353:7)
    at async Sequelize.sync (C:\_git\Portfolio\backend\node_modules\sequelize\src\sequelize.js:816:9) {
  name: 'SequelizeDatabaseError',
  parent: Error: Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.
      at Packet.asError (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\_git\Portfolio\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9) {
    code: undefined,
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.",
    sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
    parameters: undefined
  },
  original: Error: Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.
      at Packet.asError (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\_git\Portfolio\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9) {
    code: undefined,
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.",
    sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
    parameters: undefined
  },
  sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
  parameters: {}
}
2022-09-25 09:57:28 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 09:57:28 <info> (App.ts:29) undefined '❗️Error in Create users Table : ' Error
    at Query.run (C:\_git\Portfolio\backend\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\_git\Portfolio\backend\node_modules\sequelize\src\sequelize.js:641:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MySQLQueryInterface.createTable (C:\_git\Portfolio\backend\node_modules\sequelize\src\dialects\abstract\query-interface.js:229:12)
    at async Function.sync (C:\_git\Portfolio\backend\node_modules\sequelize\src\model.js:1353:7)
    at async Sequelize.sync (C:\_git\Portfolio\backend\node_modules\sequelize\src\sequelize.js:816:9) {
  name: 'SequelizeDatabaseError',
  parent: Error: Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.
      at Packet.asError (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\_git\Portfolio\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9) {
    code: undefined,
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.",
    sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
    parameters: undefined
  },
  original: Error: Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.
      at Packet.asError (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\_git\Portfolio\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9) {
    code: undefined,
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.",
    sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
    parameters: undefined
  },
  sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
  parameters: {}
}
2022-09-25 10:00:01 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:00:01 <info> (App.ts:29) undefined '❗️Error in Create users Table : ' Error
    at Query.run (C:\_git\Portfolio\backend\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\_git\Portfolio\backend\node_modules\sequelize\src\sequelize.js:641:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MySQLQueryInterface.createTable (C:\_git\Portfolio\backend\node_modules\sequelize\src\dialects\abstract\query-interface.js:229:12)
    at async Function.sync (C:\_git\Portfolio\backend\node_modules\sequelize\src\model.js:1353:7)
    at async Sequelize.sync (C:\_git\Portfolio\backend\node_modules\sequelize\src\sequelize.js:816:9) {
  name: 'SequelizeDatabaseError',
  parent: Error: Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.
      at Packet.asError (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\_git\Portfolio\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9) {
    code: undefined,
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.",
    sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
    parameters: undefined
  },
  original: Error: Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.
      at Packet.asError (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\_git\Portfolio\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\_git\Portfolio\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\_git\Portfolio\backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9) {
    code: undefined,
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'room_id' and referenced column 'id' in foreign key constraint 'chat_messages_ibfk_1' are incompatible.",
    sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
    parameters: undefined
  },
  sql: 'CREATE TABLE IF NOT EXISTS `chat_messages` (`id` INTEGER NOT NULL auto_increment , `room_id` VARCHAR(100) NOT NULL , `sender_id` VARCHAR(50) NOT NULL, `receiver_id` VARCHAR(50) NOT NULL, `file_name` VARCHAR(200), `created_at` DATETIME NOT NULL, PRIMARY KEY (`id`, `room_id`), FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;',
  parameters: {}
}
2022-09-25 10:02:02 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:02:03 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:03:39 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:03:39 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:11:25 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:11:25 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:16:23 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:16:23 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:16:55 <info> (error.ts:46) be88b4a0-3c6f-11ed-b054-0b1a29dac791 [
  Error: POST /chat/makeRoom 라우터가 없습니다.
      at error400Handler (C:\_git\Portfolio\backend\src\modules\error.ts:44:15)
      at Layer.handle [as handle_request] (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:328:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12)
      at Immediate.next (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:280:10)
      at Immediate._onImmediate (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:646:15)
      at processImmediate (internal/timers.js:466:21)
      at process.topLevelDomainCallback (domain.js:147:15)
      at process.callbackTrampoline (internal/async_hooks.js:129:24)
]
2022-09-25 10:18:53 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:18:53 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:23:07 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:23:07 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:35:31 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:35:31 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:35:37 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:35:37 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:41:37 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:41:37 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:50:11 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:50:11 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:51:33 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:51:33 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 10:52:16 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 10:52:16 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 11:15:41 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 11:15:41 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 11:17:12 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 11:17:12 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 11:17:46 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 11:17:47 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 11:24:48 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 11:24:48 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 11:24:49 <info> (error.ts:35) 3b22f710-3c79-11ed-8304-e5c75cf0f1b2 [
  ApiError: Unknown column 'ChatRooms.participant_id' in 'field list'
      at errorConverter (C:\_git\Portfolio\backend\src\modules\error.ts:15:13)
      at Layer.handle_error (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:71:5)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:326:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12)
      at next (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:280:10)
      at Layer.handle_error (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:67:12)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:326:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12) {
    statusCode: 500,
    isFatal: false
  }
]
2022-09-25 11:25:24 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 11:25:24 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 11:25:26 <info> (error.ts:35) 512c4ac0-3c79-11ed-a29f-0d4728911bfd [
  ApiError: Unknown column 'ChatParticipant.participant_id' in 'field list'
      at errorConverter (C:\_git\Portfolio\backend\src\modules\error.ts:15:13)
      at Layer.handle_error (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:71:5)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:326:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12)
      at next (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:280:10)
      at Layer.handle_error (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:67:12)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:326:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12) {
    statusCode: 500,
    isFatal: false
  }
]
2022-09-25 11:27:21 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 11:27:21 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 11:28:20 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 11:28:20 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 11:30:10 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 11:30:10 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 12:00:40 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 12:00:40 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:02:46 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:02:46 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:37:09 <info> (error.ts:35) b73c3390-3c8b-11ed-bb0d-95616196a6a2 [
  ApiError: Cannot destructure property 'user_id' of 'userInfo' as it is undefined.
      at errorConverter (C:\_git\Portfolio\backend\src\modules\error.ts:15:13)
      at Layer.handle_error (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:71:5)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:326:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12)
      at next (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:280:10)
      at Layer.handle_error (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:67:12)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:326:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12) {
    statusCode: 500,
    isFatal: false
  }
]
2022-09-25 13:43:53 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:43:53 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:44:00 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:44:00 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:44:04 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:44:04 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:44:09 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:44:09 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:45:20 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:45:20 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:47:37 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:47:37 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:48:01 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:48:01 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:48:10 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:48:10 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:55:28 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 13:55:28 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 13:55:37 <info> (error.ts:35) 4c0cc000-3c8e-11ed-9439-ddf078140965 [
  ApiError: 로그인한 이후에 이용하시기 바랍니다.
      at errorConverter (C:\_git\Portfolio\backend\src\modules\error.ts:15:13)
      at Layer.handle_error (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:71:5)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:326:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12)
      at next (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:280:10)
      at Layer.handle_error (C:\_git\Portfolio\backend\node_modules\express\lib\router\layer.js:67:12)
      at trim_prefix (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:326:13)
      at C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:286:9
      at Function.process_params (C:\_git\Portfolio\backend\node_modules\express\lib\router\index.js:346:12) {
    statusCode: 500,
    isFatal: false
  }
]
2022-09-25 14:04:39 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 14:04:39 <info> (App.ts:27) undefined '✅Success Create users Table'
2022-09-25 14:07:44 <info> (App.ts:25) undefined '✅DB connection success.'
2022-09-25 14:07:44 <info> (App.ts:27) undefined '✅Success Create users Table'
